Release 4.0.0
Saebasol/Heliotrope_deprecated pull request #184
Opened 2021-04-03 12:44 UTC by SaidBySolo

2021-04-06 13:12 UTC, SaidBySolo commented
https://github.com/getsentry/sentry-python/pull/1066 must be merged and released.

2021-04-12 02:15 UTC, kijk2869 requested changes

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/database/query.py
> +        return ranking
```suggestion
        
        return {
            "total": len(sorted_ranking),
            "list": sorted_ranking,
        }
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/database/query.py
> +            return True
```suggestion
    elif galleryinfo := await GalleryInfo.get_or_none(id=index):
        index_data = await RequestCount.create(
            index=index, count=1, title=galleryinfo.title
        )
        await index_data.save()
        return True
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/database/query.py
> +            return True
How about use ``create_or_none``

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/database/query.py
> +            tag_orm_object_list.append(tag_orm_object)
```suggestion
        tag_orm_object_list = list(
            map(
                    lambda tag_info: Tag(
                    index_id=galleryinfo.galleryid,
                    male=tag_info.get("male"),
                    female=tag_info.get("female"),
                    tag=tag_info.get("tag"),
                    url=tag_info.get("url"),
            ), galleryinfo.tags
            )
        )
            
        await asyncio.gather(
            *list(
                map(
                    lambda tag_orm_object: tag_orm_object.save(),
                    tag_orm_object_list
                )
            )
        )
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/database/query.py
> +            file_orm_object_list.append(file_orm_object)
```suggestion
        file_orm_object_list = list(
            map(
                lambda file_info: File(
                    index_id=galleryinfo.galleryid,
                    width=file_info.get("width"),
                    hash=file_info.get("hash"),
                    haswebp=file_info.get("haswebp"),
                    name=file_info.get("name"),
                    height=file_info.get("height"),
                ), galleryinfo.files
            )
        )
        
        await asyncio.gather(
            *list(
                map(
                    lambda file_orm_object: file_orm_object.save(),
                    file_orm_object_list
                )
            )
        )
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/database/query.py
> +        ]
```suggestion
        return list(map(
            lambda search_result: {
                **(await search_result.filter(id=search_result.id).values())[0],
                "tags": remove_id_and_index_id(await search_result.tags.all().values()),
                "files": remove_id_and_index_id(
                    await search_result.files.all().values()
                ),
            },
            search_result_list
        )
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/mirroring.py
> +        return to_be_loaded_list
```suggestion
        return list(set(remote_index_list) - set(local_index_list))
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/routes/about.py
> +                )
```suggestion
        if (is_json := request.args.get("json")) and (is_json.lower() == "true"):
            return json(
                {
                    "last_checked_time": manager.last_checked_time,
                    "last_mirrored_time": manager.mirroring_time,
                    "new_item": manager.new_item,
                    "server_status": manager.status,
                }
            )
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/routes/api/count.py
> +                return json({"status": 200})
```suggestion
        if (index := request.json.get("index")) and await add_request_count(index):
            return json({"status": 200})
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/database/query.py
> +        map(lambda x: int(x), await Index.all().values_list("index_id", flat=True)),
```suggestion
        map(int, await Index.all().values_list("index_id", flat=True)),
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/mirroring.py
> +        self.new_item = f"{len(index_list)}"
```suggestion
        self.new_item = str(len(index_list))
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/mirroring.py
> +        self.status = "idle"
Make it as enum

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/routes/api/hitomi/images.py
> +        return json(
```suggestion
            return not_found
        
        return json(
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/routes/api/hitomi/images.py
> +                ]
```suggestion
                "files": list(map(
                    lambda file: {
                        "name": file.name,
                        "image": shuffle_image_url(
                            image_url_from_image(int(index), file, True)
                        ),
                    }, files
                ))
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/routes/api/hitomi/search.py
> +                return json({"status": 200, "result": result})
```suggestion
        if (query := request.args.get("q")) and (result := await search_galleryinfo(query)):
            return json({"status": 200, "result": result})
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/routes/api/proxy.py
> +        if not url:
```suggestion
        if not url := solve_shuffle_image_url(shuffled_url):
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/server.py
> +    heliotrope.ctx.mirroring_manager = Mirroring(mirroring_manager_session)
```suggestion
    heliotrope.ctx.hitomi_requester = HitomiRequester(ClientSession(loop=loop))
    heliotrope.ctx.mirroring_manager = Mirroring(ClientSession(loop=loop))
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/utils/requester.py
> +    user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"
Use random user agent

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/utils/requester.py
> +    headers = {"referer": f"https://{domain}", "User-Agent": user_agent}
Use UPPER_CASE

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/utils/requester.py
> +                return tags_dict
```suggestion
                return {
                    "title": tags_model.title,
                    "thumbnail": tags_model.thumbnail,
                    "artist": tags_model.artist,
                    "group": tags_model.group,
                    "type": tags_model.hitomi_type,
                    "language": tags_model.language,
                    "series": tags_model.series,
                    "characters": tags_model.characters,
                    "tags": tags_model.tags,
                }
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/utils/shuffle.py
> +        return
Use contextlib.suppress

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/utils/shuffle.py
> +        return
Use contextlib.suppress

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/routes/api/hitomi/list.py
> +        ]
```suggestion
        split_hitomi_index_list = list(map(
            lambda i: hitomi_index_list[i * 15 : (i + 1) * 15], 
            range((len(hitomi_index_list) + 15 - 1) // 15)
        ))
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/routes/api/hitomi/list.py
> +            ]
```suggestion
            *list(map(
                lambda index: request.app.ctx.hitomi_requester.get_info_using_index(index), 
                split_hitomi_index_list[index]
            ))
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/utils/hitomi/models.py
> +            parsed_tags = []
```suggestion
        parsed_tags = []
        
        if galleryinfo_json["tags"]:
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/utils/hitomi/models.py
> +                    raise Exception
```suggestion
                if len(value := list(filter(None, ["male" if tag.get("male") else None, "female" if tag.get("female") else None]))) > 1:
                    raise Exception

            parsed_tags.append({"value": f"{value[0] if value else 'tag'}:{tag['tag']}", "url": tag["url"]})
```

2021-04-12 02:15 UTC, kijk2869 commented on heliotrope/utils/hitomi/models.py
> +                return []
Should it returns an empty list when elements is empty list?

2021-04-12 02:21 UTC, kijk2869 commented on heliotrope/utils/hitomi/models.py
> +                return []
If not, combine those two if comprehensions.

2021-04-12 12:24 UTC, SaidBySolo commented on heliotrope/routes/about.py
> +                )
Syntax error
```suggestion
        if is_json := request.args.get("json"):
            if is_json.lower() == "true":
                return json(
                    {
                        "last_checked_time": manager.last_checked_time,
                        "last_mirrored_time": manager.mirroring_time,
                        "new_item": manager.new_item,
                        "server_status": manager.status,
                    }
                )
```

2021-04-12 12:29 UTC, SaidBySolo commented on heliotrope/routes/api/hitomi/images.py
> +        return json(
files possibly unbound

2021-04-12 12:33 UTC, SaidBySolo commented on heliotrope/routes/api/hitomi/search.py
> +                return json({"status": 200, "result": result})
Syntax Error

2021-04-12 12:39 UTC, kijk2869 commented on heliotrope/routes/api/hitomi/search.py
> +                return json({"status": 200, "result": result})
I edited it

2021-04-12 12:40 UTC, kijk2869 commented on heliotrope/routes/about.py
> +                )
> Syntax error
> ```suggestion
>         if is_json := request.args.get("json"):
>             if is_json.lower() == "true":
>                 return json(
>                     {
>                         "last_checked_time": manager.last_checked_time,
>                         "last_mirrored_time": manager.mirroring_time,
>                         "new_item": manager.new_item,
>                         "server_status": manager.status,
>                     }
>                 )
> ```
> 

Do not use this, i edited it.

2021-06-18 09:42 UTC, merged